perfere uppcase variable names in build scripts

diff --git a/.github/actions/get-app-version/action.yml b/.github/actions/get-app-version/action.yml
--- a/.github/actions/get-app-version/action.yml
+++ b/.github/actions/get-app-version/action.yml
@@ -1,19 +1,19 @@
 name: Get app version
 outputs:
-  current_app_version:
-    value: ${{ steps.app_version.outputs.current_app_version }}
-  current_major_segment:
-    value: ${{ steps.app_version.outputs.current_major_segment }}
-  current_minor_segment:
-    value: ${{ steps.app_version.outputs.current_minor_segment }}
-  current_patch_segment:
-    value: ${{ steps.app_version.outputs.current_patch_segment }}
-  next_major_app_version:
-    value: ${{ steps.app_version.outputs.next_major_app_version }}
-  next_minor_app_version:
-    value: ${{ steps.app_version.outputs.next_minor_app_version }}
-  next_patch_app_version:
-    value: ${{ steps.app_version.outputs.next_patch_app_version }}
+  CURRENT_APP_VERSION:
+    value: ${{ steps.app_version.outputs.CURRENT_APP_VERSION }}
+  CURRENT_MAJOR_SEGMENT:
+    value: ${{ steps.app_version.outputs.CURRENT_MAJOR_SEGMENT }}
+  CURRENT_MINOR_SEGMENT:
+    value: ${{ steps.app_version.outputs.CURRENT_MINOR_SEGMENT }}
+  CURRENT_PATCH_SEGMENT:
+    value: ${{ steps.app_version.outputs.CURRENT_PATCH_SEGMENT }}
+  NEXT_MAJOR_APP_VERSION:
+    value: ${{ steps.app_version.outputs.NEXT_MAJOR_APP_VERSION }}
+  NEXT_MINOR_APP_VERSION:
+    value: ${{ steps.app_version.outputs.NEXT_MINOR_APP_VERSION }}
+  NEXT_PATCH_APP_VERSION:
+    value: ${{ steps.app_version.outputs.NEXT_PATCH_APP_VERSION }}
 runs:
   using: 'composite'
   steps:
@@ -21,34 +21,34 @@ runs:
     id: app_version
     shell: bash
     run: |
-      current_app_version=$(sed -znE -e "s|.*<VersionPrefix>[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]*</VersionPrefix>.*|\1|p" src/WebApplication1/WebApplication1.csproj)
-      [[ -z $current_app_version ]] && (echo "::error::Version not found" && exit 1)
+      CURRENT_APP_VERSION=$(sed -znE -e "s|.*<VersionPrefix>[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]*</VersionPrefix>.*|\1|p" src/WebApplication1/WebApplication1.csproj)
+      [[ -z $CURRENT_APP_VERSION ]] && (echo "::error::Version not found" && exit 1)
 
-      echo "current_app_version=$current_app_version"
-      echo "current_app_version=$current_app_version" >> $GITHUB_OUTPUT
+      echo "CURRENT_APP_VERSION=$CURRENT_APP_VERSION"
+      echo "CURRENT_APP_VERSION=$CURRENT_APP_VERSION" >> $GITHUB_OUTPUT
 
-      current_major_segment=$(echo $current_app_version | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\1|p")
-      current_minor_segment=$(echo $current_app_version | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\2|p")
-      current_patch_segment=$(echo $current_app_version | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\3|p")
+      CURRENT_MAJOR_SEGMENT=$(echo $CURRENT_APP_VERSION | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\1|p")
+      CURRENT_MINOR_SEGMENT=$(echo $CURRENT_APP_VERSION | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\2|p")
+      CURRENT_PATCH_SEGMENT=$(echo $CURRENT_APP_VERSION | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\3|p")
 
-      echo "current_major_segment=$current_major_segment"
-      echo "current_major_segment=$current_major_segment" >> $GITHUB_OUTPUT
+      echo "CURRENT_MAJOR_SEGMENT=$CURRENT_MAJOR_SEGMENT"
+      echo "CURRENT_MAJOR_SEGMENT=$CURRENT_MAJOR_SEGMENT" >> $GITHUB_OUTPUT
       
-      echo "current_minor_segment=$current_minor_segment"
-      echo "current_minor_segment=$current_minor_segment" >> $GITHUB_OUTPUT
+      echo "CURRENT_MINOR_SEGMENT=$CURRENT_MINOR_SEGMENT"
+      echo "CURRENT_MINOR_SEGMENT=$CURRENT_MINOR_SEGMENT" >> $GITHUB_OUTPUT
       
-      echo "current_patch_segment=$current_patch_segment"
-      echo "current_patch_segment=$current_patch_segment" >> $GITHUB_OUTPUT
+      echo "CURRENT_PATCH_SEGMENT=$CURRENT_PATCH_SEGMENT"
+      echo "CURRENT_PATCH_SEGMENT=$CURRENT_PATCH_SEGMENT" >> $GITHUB_OUTPUT
 
-      next_major_segment=$(echo $current_major_segment | awk '{$NF += 1 ; print}')
-      next_minor_segment=$(echo $current_minor_segment | awk '{$NF += 1 ; print}')
-      next_patch_segment=$(echo $current_patch_segment | awk '{$NF += 1 ; print}')
+      NEXT_MAJOR_SEGMENT=$(echo $CURRENT_MAJOR_SEGMENT | awk '{$NF += 1 ; print}')
+      NEXT_MINOR_SEGMENT=$(echo $CURRENT_MINOR_SEGMENT | awk '{$NF += 1 ; print}')
+      NEXT_PATCH_SEGMENT=$(echo $CURRENT_PATCH_SEGMENT | awk '{$NF += 1 ; print}')
 
-      echo "next_major_app_version=$next_major_segment.0.0"
-      echo "next_major_app_version=$next_major_segment.0.0" >> $GITHUB_OUTPUT
+      echo "NEXT_MAJOR_APP_VERSION=$NEXT_MAJOR_SEGMENT.0.0"
+      echo "NEXT_MAJOR_APP_VERSION=$NEXT_MAJOR_SEGMENT.0.0" >> $GITHUB_OUTPUT
 
-      echo "next_minor_app_version=$current_major_segment.$next_minor_segment.0"
-      echo "next_minor_app_version=$current_major_segment.$next_minor_segment.0" >> $GITHUB_OUTPUT
+      echo "NEXT_MINOR_APP_VERSION=$CURRENT_MAJOR_SEGMENT.$NEXT_MINOR_SEGMENT.0"
+      echo "NEXT_MINOR_APP_VERSION=$CURRENT_MAJOR_SEGMENT.$NEXT_MINOR_SEGMENT.0" >> $GITHUB_OUTPUT
       
-      echo "next_patch_app_version=$current_major_segment.$current_minor_segment.$next_patch_segment"
-      echo "next_patch_app_version=$current_major_segment.$current_minor_segment.$next_patch_segment" >> $GITHUB_OUTPUT
+      echo "NEXT_PATCH_APP_VERSION=$CURRENT_MAJOR_SEGMENT.$CURRENT_MINOR_SEGMENT.$NEXT_PATCH_SEGMENT"
+      echo "NEXT_PATCH_APP_VERSION=$CURRENT_MAJOR_SEGMENT.$CURRENT_MINOR_SEGMENT.$NEXT_PATCH_SEGMENT" >> $GITHUB_OUTPUT
